### PR TITLE
Feature service

### PR DESCRIPTION
**Pull request by forman**
* added three new server endpoints `/features.json` with GET and POST and `/features/{dataset}.json` with GET
* features can be configured in `config.jaml` using the `Features` section. It's `Path` setting can be a GeoJSON file or Shapefile or a wildcard that collects many of them.
* new module `logtime` that provides the `log_time` context manager for logging times
* new `fiona` and `shapely` dependencies

### CODE REVIEW

**Comment by forman** [comment]
> The openapi description of the find features is missing an explanation of the bounding box - in particular that it shouldn't be combined with geom

Will do.

> Within the time series part of the api, we call a bounding box 'bounds' and pass it is an object (which of course is not possible for a query parameter). We should try to strive for a somewhat consistent naming at the very least.

That's true. However I find `bounds` is not the right name for what it is: a box-shaped polygon. A bounds is a property of something, e.g. bounds of another polygon or the dataset coverage.

> 'query' is a rather unfortunate name for a query parameter. 

Well, this is just how many other REST APIs call their query string / expression. Any suggestions?

> the new endpoints end on'.json' in 'app.py', but not in the api. It should be a consistent naming.

Yepp, I thought about this yesterday. Proposal: remove the `.json` extension from enpoint URLs.

> When passing a feature collection to find intersections, only the first feature of the collection is considered in find_features.py.

Why is this a major issue? Who said, it should be different?

> In __find_features, 'query_expr' is not evaluated, In __find_features, 'comb_op' is not evaluated

Next PR. They currently raise NotImplementedError.

**Comment by forman** [comment]
General comment: please place your comments next to the change where it applies to.

**Comment by TonioF** [comment]
>> When passing a feature collection to find intersections, only the first feature of the collection is considered in find_features.py.

>Why is this a major issue? Who said, it should be different?

Extreme case: We have a feature collection with two features: A very small one and a very large one. Our implementation would just take the very small one, as it comes first, and miss all the intersections with the very large one.
Other example: We are looking for lakes in three different regions. We would only be able to find lakes for one region.

**Comment by forman** [comment]
We have not yet specified at all, how the API should behave. My decision was to take the first feature, because for multiple features it is unspecified what should be done with their geometries, combined, AND-ed, OR-ed? The API call expects a single geometry object.

**Comment by TonioF** [comment]
>>the new endpoints end on'.json' in 'app.py', but not in the api. It should be a consistent naming.

>Yepp, I thought about this yesterday. Proposal: remove the .json extension from enpoint URLs.

This one is still missing.

**Comment by forman** [comment]
I resolve conflicts...

**Pull request merged**
